import { prisma } from '@/lib/prisma';
import { formatCurrency } from '@/lib/utils';
import PrintTrigger from '@/components/finance/PrintTrigger'; // Now this will work

export const dynamic = 'force-dynamic';

export default async function PrintFinancePage({ searchParams }: { searchParams: Promise<{ query?: string }> }) {
  const params = await searchParams;
  const query = params.query || '';

  const whereCondition = query ? {
    OR: [
      { student: { fullName: { contains: query, mode: 'insensitive' as const } } },
      { invoiceNumber: { contains: query, mode: 'insensitive' as const } }
    ]
  } : {};

  const invoices = await prisma.invoice.findMany({
    where: whereCondition,
    take: 1000, 
    orderBy: { issueDate: 'desc' },
    include: { 
      student: { include: { level: true } } 
    }
  });

  const grandTotal = invoices.reduce((sum, inv) => sum + Number(inv.totalAmount), 0);
  const grandPaid = invoices.reduce((sum, inv) => sum + Number(inv.amountPaid), 0);
  const grandBalance = grandTotal - grandPaid;

  return (
    <div className="min-h-screen bg-white text-black font-sans p-8 print:p-0">
      <PrintTrigger />

      <div className="mb-6 border-b-2 border-black pb-4 flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold uppercase tracking-wide text-black">Invoice Ledger</h1>
          <div className="text-sm mt-1 text-gray-600">
             <span>Date: {new Date().toLocaleDateString()}</span>
             {/* 🟢 Fixed Quotes here: &quot;{query}&quot; */}
             {query && <span className="ml-4 font-bold">Filter: &quot;{query}&quot;</span>}
          </div>
        </div>
        <div className="text-right">
          <p className="font-bold text-lg">Yosola Schools</p>
          <p className="text-xs uppercase text-gray-500">Financial Records</p>
        </div>
      </div>

      {/* ... Rest of the table code remains the same ... */}
       <table className="w-full text-left text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="py-2 font-bold w-24">Date</th>
            <th className="py-2 font-bold w-28">Invoice #</th>
            <th className="py-2 font-bold">Student Name</th>
            <th className="py-2 font-bold w-20">Class</th>
            <th className="py-2 font-bold text-right w-28">Total</th>
            <th className="py-2 font-bold text-right w-28">Paid</th>
            <th className="py-2 font-bold text-right w-28">Balance</th>
          </tr>
        </thead>
        <tbody>
          {invoices.map((inv) => {
            const balance = Number(inv.totalAmount) - Number(inv.amountPaid);
            return (
              <tr key={inv.id} className="border-b border-gray-300 break-inside-avoid">
                <td className="py-2 text-gray-700">
                    {new Date(inv.issueDate).toLocaleDateString()}
                </td>
                <td className="py-2 font-mono text-xs">{inv.invoiceNumber}</td>
                <td className="py-2 font-medium">{inv.student.fullName}</td>
                <td className="py-2 text-xs uppercase">{inv.student.level?.name}</td>
                <td className="py-2 text-right">{formatCurrency(Number(inv.totalAmount))}</td>
                <td className="py-2 text-right text-gray-600">{formatCurrency(Number(inv.amountPaid))}</td>
                <td className={`py-2 text-right font-bold ${balance > 0 ? 'text-black' : 'text-gray-400'}`}>
                  {balance > 0 ? formatCurrency(balance) : '-'}
                </td>
              </tr>
            );
          })}
          
          <tr className="border-t-2 border-black font-bold text-sm bg-gray-100 print:bg-transparent">
            <td colSpan={4} className="py-3 text-right pr-4 uppercase">Grand Totals:</td>
            <td className="py-3 text-right">{formatCurrency(grandTotal)}</td>
            <td className="py-3 text-right">{formatCurrency(grandPaid)}</td>
            <td className="py-3 text-right">{formatCurrency(grandBalance)}</td>
          </tr>
        </tbody>
      </table>

      <div className="mt-8 text-center text-[10px] text-gray-400">
         <p>Generated by Yosola School Manager • {invoices.length} Records</p>
      </div>
    </div>
  );
}
